apiVersion: v2
name: kubevoip
description: A Kubernetes operator for scalable SIP platforms.
type: application
version: 0.2.4
appVersion: "0.2.4"
home: https://kubevoip.com
keywords: [voip, asterisk, sip, kubernetes, operator]
sources:
  - https://github.com/danohn/kubevoip
