image:
  repository: ghcr.io/danohn/kubevoip
  tag: "v0.2.3"
  pullPolicy: IfNotPresent

asteriskImage:
  repository: ghcr.io/danohn/kubevoip-asterisk
  tag: "v0.2.3"

asteriskWorkerImage:
  repository: ghcr.io/danohn/kubevoip-asterisk-worker
  tag: "v0.2.3"

kamailioImage:
  repository: ghcr.io/danohn/kubevoip-kamailio
  tag: "v0.2.3"

rtpengineImage:
  repository: ghcr.io/danohn/kubevoip-rtpengine
  tag: "v0.2.3"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
