image:
  repository: ghcr.io/kubevoip/kubevoip
  tag: "v0.6.6"
  pullPolicy: IfNotPresent

operator:
  replicas: 1
  highAvailability:
    enabled: false
    peeringName: ""

asteriskImage:
  repository: ghcr.io/kubevoip/kubevoip-asterisk
  tag: "v0.5.0"

kamailioImage:
  repository: ghcr.io/kubevoip/kubevoip-kamailio
  tag: "v0.5.0"

rtpengineImage:
  repository: ghcr.io/kubevoip/kubevoip-rtpengine
  tag: "v0.5.0"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
