image:
  repository: ghcr.io/danohn/kubevoip
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

asteriskImage:
  repository: ghcr.io/danohn/kubevoip-asterisk
  tag: "v0.1.0"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
