apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevoip.fullname" . }}
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubevoip.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kubevoip.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubevoip.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --namespace={{ .Release.Namespace }}
          env:
            - name: KUBEVOIP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBEVOIP_ASTERISK_IMAGE
              value: "{{ .Values.asteriskImage.repository }}:{{ .Values.asteriskImage.tag }}"
            - name: KUBEVOIP_ASTERISK_WORKER_IMAGE
              value: "{{ .Values.asteriskWorkerImage.repository }}:{{ .Values.asteriskWorkerImage.tag }}"
            - name: KUBEVOIP_KAMAILIO_IMAGE
              value: "{{ .Values.kamailioImage.repository }}:{{ .Values.kamailioImage.tag }}"
            - name: KUBEVOIP_RTPENGINE_IMAGE
              value: "{{ .Values.rtpengineImage.repository }}:{{ .Values.rtpengineImage.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
