{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevoip.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kubevoip.com"]
    resources: ["asterisks", "asterisks/status", "asterisks/finalizers", "networkprofiles", "networkprofiles/status", "networkprofiles/finalizers", "sipusers", "sipusers/status", "sipusers/finalizers", "mediarelays", "mediarelays/status", "mediarelays/finalizers", "asteriskpools", "asteriskpools/status", "asteriskpools/finalizers", "sipgateways", "sipgateways/status", "sipgateways/finalizers"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/status", "deployments/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevoip.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevoip.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevoip.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
