{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubevoip.fullname" . }}-{{ .Release.Namespace }}-discovery
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevoip.fullname" . }}-{{ .Release.Namespace }}-discovery
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevoip.fullname" . }}-{{ .Release.Namespace }}-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevoip.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevoip.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kubevoip.com"]
    resources: ["networkprofiles", "networkprofiles/status", "networkprofiles/finalizers", "callscopes", "callscopes/status", "callscopes/finalizers", "dialpolicies", "dialpolicies/status", "dialpolicies/finalizers", "sipusers", "sipusers/status", "sipusers/finalizers", "siptrunks", "siptrunks/status", "siptrunks/finalizers", "callroutes", "callroutes/status", "callroutes/finalizers", "mediarelays", "mediarelays/status", "mediarelays/finalizers", "asteriskpools", "asteriskpools/status", "asteriskpools/finalizers", "sipgateways", "sipgateways/status", "sipgateways/finalizers"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/status", "deployments/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevoip.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevoip.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevoip.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevoip.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
