apiVersion: kubevoip.com/v1alpha1
kind: NetworkProfile
metadata:
  name: public
  namespace: asterisk-demo
spec:
  externalAddress:
    value: 203.0.113.10
  localNetworks:
    - 10.0.0.0/8
---
apiVersion: kubevoip.com/v1alpha1
kind: MediaRelay
metadata:
  name: home
  namespace: asterisk-demo
spec:
  replicas: 2
  networkProfileRef:
    name: public
  media:
    start: 20000
    end: 20039
  network:
    mode: Service
    service:
      type: ClusterIP
---
apiVersion: kubevoip.com/v1alpha1
kind: AsteriskPool
metadata:
  name: applications
  namespace: asterisk-demo
spec:
  replicas: 2
  applications:
    echoExtension: "600"
